[package]
name = "ddd-server"
edition.workspace = true
license.workspace = true
default-run = "ddd-server"

[dependencies]
anyhow = "1.0.102"
arc-swap = "1.9.1"
bpaf = "0.9.26"
cini = "1.0.0"
heapless = "0.9.3"
jiff = "0.2.28"
log = { version = "0.4.32", features = ["max_level_debug", "std"] }
noise-protocol = "0.2.1"
orion = "0.17.15"
rand = { version = "0.10.1", default-features = false, features = ["sys_rng"] }
scc = "3.7.1"
signal-hook = "0.4.4"
yansi = { version = "1.0.1", features = ["detect-env"] }
zeroize = "1.8.1"

[build-dependencies]
ddd-formats = { path = "../formats" }

[lints]
workspace = true
