use std::sync::mpsc::{Receiver, SyncSender};

use crate::buffer::Buffer;
use crate::message::Message;

mod base64;
mod buffer;
mod client;
mod clients;
pub mod config;
mod connection;
pub mod courses;
mod credential;
pub mod crypto;
mod dir_entry;
pub mod flood;
pub mod formats;
mod frequency;
mod http;
mod item;
mod item_weights;
mod kart;
mod listener;
pub mod logger;
mod message;
mod mmr;
pub mod options;
mod pack;
mod player;
mod race_client_stats;
mod receiver;
mod result_ext;
mod results;
mod room;
mod rooms;
mod s3;
mod sender;
pub mod server;
mod shard;
pub mod sighup;
mod sorted;
pub mod storage;
pub mod update;
mod updater;
mod webhook;
mod website;
mod weight;

type BufferSender = SyncSender<Buffer>;
type BufferReceiver = Receiver<Buffer>;
type MessageSender = SyncSender<Message>;
type MessageReceiver = Receiver<Message>;
