use std::sync::mpsc::{Receiver, SyncSender};

use crate::buffer::Buffer;
use crate::message::Message;

mod buffer;
mod client;
mod clients;
pub mod config;
mod connection;
pub mod crypto;
pub mod flood;
pub mod formats;
mod frequency;
mod item;
mod item_weights;
mod kart;
mod listener;
pub mod logger;
mod message;
mod mmr;
pub mod options;
mod pack;
mod player;
mod receiver;
mod results;
mod room;
mod rooms;
mod sender;
pub mod server;
mod shard;
pub mod sighup;
pub mod update;
mod updater;
mod weight;

type BufferSender = SyncSender<Buffer>;
type BufferReceiver = Receiver<Buffer>;
type MessageSender = SyncSender<Message>;
type MessageReceiver = Receiver<Message>;
