name: Build ddd-server

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - windows-2025
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: -D warnings
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ddd-server-${{ matrix.os }}
          path: |
            target/release/ddd-server
            target/release/ddd-server.exe

  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - windows-2025
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: -D warnings
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: cargo test

  format:
    name: Format
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - windows-2025
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format
        run: cargo fmt --check
